name = "mito-shogi-api"
main = "src/index.ts"
compatibility_date = "2024-11-11"
send_metrics = true
compatibility_flags = ["nodejs_compat_v2"]
logpush = true

# Cloudflare Workers KV namespaces
kv_namespaces = []

d1_databases = [
  { binding = "DB", database_name = "mito-shogi", database_id = "ee3fbbc0-06ef-4ed4-baa7-658d0f664aee" },
]

# [[unsafe.bindings]]
# name = "HONO_RATE_LIMITER"
# type = "ratelimit"
# namespace_id = "1001"
# simple = { limit = 100, period = 60 }

# Cron Events
[triggers]
crons = ["*/5 * * * *"]

[env.dev]

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true

[env.dev.observability]
enabled = true
head_sampling_rate = 1

[env.dev.observability.logs]
enabled = true

[dev]
ip = "0.0.0.0"
port = 8787
