name = "mito-shogi-api"
main = "src/index.ts"
compatibility_date = "2024-11-11"
send_metrics = true
compatibility_flags = ["nodejs_compat_v2"]
logpush = true

# Cloudflare Workers KV namespaces
kv_namespaces = [
  { binding = "CACHE", id = "60fc87bcd9a443b385b186a67864ec8b", preview_id = "5b7d4f9a4a434dee94666845cbd6d23d" },
]

d1_databases = [
  { binding = "DB", database_name = "mito-shogi", database_id = "3aa4f6e7-4514-4bf0-98bd-df87e7cd2be5" },
]

# Cron Events
[triggers]
crons = []

[env.dev]

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true

[env.dev.observability]
enabled = true
head_sampling_rate = 1

[env.dev.observability.logs]
enabled = true

[dev]
ip = "0.0.0.0"
port = 8787
